#!/bin/bash
#Report Generation

arr[0]="Delhi"
arr[1]="Chennai"
arr[2]="Kolkata"
arr[3]="Mumbai"

arr1[0]="@yahoo.com"
arr1[1]="@gmail.com"
arr1[2]="@hotmail.com"
arr1[3]="@rediffmail.com"

for i in {0..100}
do 
  ran=$[$RANDOM%3]
  city=${arr[$ran]}
  POS=1
  LEN=5  	#lenght upto 5 characters
  str1=$( echo "$RANDOM%10000" )
  usern="${str1:$POS:$LEN}"
  ran1=$RANDOM%3
  hostn=${arr1[$ran1]}
  echo "$usern@$hostn		$city		$((9876500000 + $RANDOM%1000000000))">> subscribers.txt

done
